version: '3.8'

services:
  test:
    build:
      dockerfile: itbdehaze.dockerfile
      context: .

    command: ["bash", "-c", "python test.py --imagenet_model SwinTransformerV2 --cfg /ITBDehaze/configs/swinv2/swinv2_base_patch4_window8_256.yaml --model_save_dir /ITBDehaze/output_img/test/best_result --ckpt_path /ITBDehaze/checkpoints/best.pkl --hazy_data '/ITBDehaze/itb-data' --cropping 4"]
    volumes:
      - /home/caitlinhaddow/Documents/Code/ITBdehaze/configs:/ITBDehaze/configs
      - /home/caitlinhaddow/Documents/Code/ITBdehaze/output_img:/ITBDehaze/output_img
      - /home/caitlinhaddow/Documents/Code/ITBdehaze/checkpoints:/ITBDehaze/checkpoints
      - /home/caitlinhaddow/Documents/Code/ITBdehaze/itb-data:/itb-data/configs
