# Use the official Conda base image with Python 3.7
FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

# Set working directory
WORKDIR /ITBdehaze

# required for opencv
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN conda install -c conda-forge timm==1.0.15 -y
RUN pip install opencv-python scikit-image tensorboardx==2.6.2.2 yacs "numpy<2"

COPY . .

CMD ["bash", "-c", "python test.py --imagenet_model SwinTransformerV2 --cfg configs/swinv2/swinv2_base_patch4_window8_256.yaml --model_save_dir ./output_result --ckpt_path ./weights/best.pkl --hazy_data Test1 --cropping 6"]



# TO BUILD IMAGE
# hare build -t ceh94/itb_test .

# TO RUN IMAGE
# hare run --rm --gpus '"device=0,1"' --shm-size=128g \
# --mount type=bind,source=/homes/ceh94/ITBdehaze/weights,target=/ITBdehaze/weights \
# --mount type=bind,source=/homes/ceh94/ITBdehaze/output_result,target=/ITBdehaze/output_result \
# --mount type=bind,source=/homes/ceh94/ITBdehaze/input_data,target=/ITBdehaze/input_data \
# ceh94/itb_test

# hare run --rm --gpus '"device=0,1"' --shm-size=128g \
# --mount type=bind,source=/mnt/faster0/ceh94/ITBdehaze/weights,target=/ITBdehaze/weights \
# --mount type=bind,source=/mnt/faster0/ceh94/ITBdehaze/output_result,target=/ITBdehaze/output_result \
# --mount type=bind,source=/mnt/faster0/ceh94/ITBdehaze/input_data,target=/ITBdehaze/input_data \
# ceh94/itb_test

# docker system prune ## run every so often to clear out system

